### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by NTMan** [octris/ncurses#1]
Link to documentation is broken
http://doc.octris.org/org.octris.ncurses/

404 Not Found

nginx/1.4.6 (Ubuntu)

**Comment by aurora** [comment]
Thanks for your interest in this ... yep, the API documentation is currently offline for all my libraries for quite a while now. Reason is that i switched the documentation tool and did not finish setting it up on the server. I think i'll have to fix this finally ... i think i'll have some time for this at the weekend.

**Comment by aurora** [comment]
The source documentation is available again:

http://octris.org/doc/octris/ncurses/html/

It's not perfect, yet, but better than nothing i think ...

If you are interested in other projects, i've put up some more documentation at: http://octris.org/doc/

Documentation will get updated nightly (CET).
